{{- if .Values.servicemonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "lab2-app.fullname" . }}
  labels:
    {{- include "lab2-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "lab2-app.fullname" . }}
  endpoints:
    - port: http
      interval: {{ .Values.servicemonitor.interval }}
      path: {{ .Values.servicemonitor.path }}
{{- end }}